### PR TITLE
Feature/OperationHealth

### PR DESCRIPTION
**Pull request by BRCDel**
Full-scale refactoring of existing code to match Java best practices.
Complete Javadoc documentation with consistent style.
Cleaner comments across the project.
Warnings cleanup.
Typos cleanup.

### CODE REVIEW

**Review by Luke270601 — APPROVED** [review]
Nicely Done

**Review by X2ThaHeart — CHANGES_REQUESTED** [review]
Looks great, however, see with your functions on app main, you've called your object:
ArrayList<City> biggest3Capitals = Sql.getNBiggestWorldCapitals(con, 3);
"biggest3Capitals" Can you change it so it doesn't matter what number is in limit, so just to be something like "biggestNCapitals" it seems a bit strange to limit the name of the object, when the number might change, or if we have to build in something more dynamic. The rest of the team have gone with a dynamic approach. Also, can you change your limit to 10. Apart from that its great, checked through the whole thing, well done.

**Review by CamyH — APPROVED** [review]
Looks good

**Comment by BRCDel** [comment]
Addressing requested changes

**Pull request closed without merging**
